export const GET_MIDI_DEVICES = "GET_MIDI_DEVICES";
export const GET_MIDI_DEVICES_SUCCESS = "GET_MIDI_DEVICES_SUCCESS";
export const GET_MIDI_DEVICES_FAILURE = "GET_MIDI_DEVICES_FAILURE";

export const SELECT_MIDI_DEVICE = "SELECT_MIDI_DEVICE";

export const START_RECORDING_MIDI = "START_RECORDING_MIDI";
export const START_MIDI = "START_MIDI";
export const STOP_MIDI = "STOP_MIDI";

export const MAP_MIDI_COMMAND = "MAP_MIDI_COMMAND";

export const SELECT_CURRENT_MIDI_KEY = "SELECT_CURRENT_MIDI_KEY";


