export const GET_COLOR_LIST_SUCCESS = "GET_COLOR_LIST_SUCCESS";

export const SEND_COLOR_MESSAGE = "SEND_COLOR_MESSAGE";
export const SEND_COLOR_MESSAGE_SUCCESS = "SEND_COLOR_MESSAGE_SUCCESS";
export const SEND_COLOR_MESSAGE_FAILURE = "SEND_COLOR_MESSAGE_FAILURE";

export const CHANGE_COLOR = "CHANGE_COLOR";