export const GET_AUDIO_LIST_SUCCESS = "GET_AUDIO_LIST_SUCCESS";

export const SEND_AUDIO_REQUEST = "SEND_AUDIO_REQUEST";
export const SEND_AUDIO_REQUEST_SUCCESS = "SEND_AUDIO_REQUEST_SUCCESS";
export const SEND_AUDIO_REQUEST_FAILURE = "SEND_AUDIO_REQUEST_FAILURE";

export const SET_AUDIO_FILE = "SET_AUDIO_FILE";

export const CHANGE_AUDIO_TIMER = "CHANGE_AUDIO_TIMER";
export const CHANGE_AUDIO_COUNT = "CHANGE_AUDIO_COUNT";